# <font color="blue"> MBA em Ciência de Dados</font>
# <font color="blue">Programação para Ciência de Dados</font>

## <font color="blue">Numpy Parte II e Matplotlib - Avaliação</font>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**
---

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Exercício 1)
Qual dos códigos abaixo utiliza corretamente broadcasting para somar o vetor `v` em cada **coluna** da matriz `A`, sendo que `v` e `A` são definidos como:
```python
A = np.zeros((4,4))
v = np.arange(4)
```

a) A[,:] + v<br>
b) A + v<br>
c) A + v.T<br>
d) A + v.reshape(4,1)

In [15]:
A = np.zeros((4,4))
v = np.arange(4)
A + v.reshape(4,1)

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

### Exercício 2)
Qual das alternativas explica corretamente como o array `W` está sendo calculado no código abaixo?
```python
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
```

a) O array `W` possui 10 elementos como resultado da soma dos arrays `u` e `v`, onde `u` é complementado com zeros durante o broadcasting.<br>
b) O array `W` possui 7 elementos como resultado da soma dos arrays `u` e `v`, onde os três útlimos elementos de `v` são descartados no broadcasting.<br>
c) O array `W` é uma matriz com 7 linhas e 10 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 linhas e o array `u` em 10 linhas.<br>
d) O array `W` é uma matriz com 10 linhas e 7 colunas gerado a partir da soma das matriz obtidas do broadcasting do array `v` em 7 colunas e do array `u` em 10 linhas.<br>

In [21]:
u = np.random.randint(0,30,7)
v = np.random.randint(0,30,10).reshape(10,1)

W = v + u
v

array([[ 1],
       [16],
       [25],
       [ 9],
       [22],
       [ 2],
       [11],
       [ 6],
       [ 2],
       [ 4]])

### Exercício 3)
Considere a matriz abaixo. Utilizando redução por média, encontre o **índice da linha** que possui a maior média dos elementos.
```python
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])
```
a) linha de índice 8<br>
b) linha de índice 0<br>
c) linha de índice 5<br>
d) linha de índice 9

In [24]:
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])


idx = 0
dicionario = {}
for row in A:
    dicionario[idx] = np.mean(row)
    idx += 1
    
dicionario
    


{0: 5.3,
 1: 4.7,
 2: 2.5,
 3: 2.9,
 4: 3.7,
 5: 4.4,
 6: 4.6,
 7: 4.5,
 8: 6.0,
 9: 3.5}

### Exercício 4) 
Considerando a matriz `A` do exercício anterior, qual o **índice da coluna** que possui a menor soma de valores?

a) linha 8<br>
b) linha 0<br>
c) linha 2<br>
d) linha 9

In [25]:
#Solucao

idx = 0
dicionario = {}
for row in A:
    dicionario[idx] = np.sum(row)
    idx += 1
    
dicionario

{0: 53, 1: 47, 2: 25, 3: 29, 4: 37, 5: 44, 6: 46, 7: 45, 8: 60, 9: 35}

### Exercício 5)
Suponha que a variável `A` no código abaixo é uma matriz com $n$ linhas e $m$ colunas. O que o código está realizando?
```python
Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,0]] = -1
```
a) Substituindo o maior valor de cada coluna por -1<br>
b) Substituindo o maior valor de cada linha por -1<br>
c) Substituindo o menor valor de cada linha por -1<br>
d) Substituindo o menor valor de cada coluna por -1

In [26]:
# Solucao
A = np.array([[5, 2, 3, 6, 1, 5, 7, 7, 8, 9], [8, 8, 3, 5, 0, 1, 4, 8, 3, 7], 
              [8, 0, 0, 4, 2, 0, 2, 6, 0, 3], [5, 0, 0, 4, 4, 3, 5, 8, 0, 0], 
              [2, 4, 2, 5, 3, 4, 9, 8, 0, 0], [6, 7, 4, 8, 5, 1, 3, 5, 4, 1], 
              [6, 8, 0, 5, 2, 9, 3, 6, 1, 6], [5, 5, 2, 9, 0, 5, 5, 8, 2, 4], 
              [8, 8, 1, 8, 4, 1, 8, 9, 7, 6], [5, 6, 0, 9, 0, 4, 9, 0, 2, 0]])

Aargs = np.argsort(A)
A[np.arange(A.shape[0]),Aargs[:,0]] = -1

In [27]:
A

array([[ 5,  2,  3,  6, -1,  5,  7,  7,  8,  9],
       [ 8,  8,  3,  5, -1,  1,  4,  8,  3,  7],
       [ 8, -1,  0,  4,  2,  0,  2,  6,  0,  3],
       [ 5, -1,  0,  4,  4,  3,  5,  8,  0,  0],
       [ 2,  4,  2,  5,  3,  4,  9,  8, -1,  0],
       [ 6,  7,  4,  8,  5, -1,  3,  5,  4,  1],
       [ 6,  8, -1,  5,  2,  9,  3,  6,  1,  6],
       [ 5,  5,  2,  9, -1,  5,  5,  8,  2,  4],
       [ 8,  8, -1,  8,  4,  1,  8,  9,  7,  6],
       [ 5,  6, -1,  9,  0,  4,  9,  0,  2,  0]])